### ISSUE TITLE
oh my zsh up arrow completion

### ISSUE THREAD

**Issue by BullShark** [robbyrussell/oh-my-zsh#1720]
I was told to make a bug from the facebook page (or maybe it was twitter). This bug is very reproducible. I am using Linux Mint 14 with Cinnamon, but it probably occurs elsewhere too. 

When I type

ssh "up arrow key" "up arrow key"

It should go through the history only displaying the last commands that began with ssh. However, it does not under Linux Mint. It just cycles through history ignoring whatever I already typed.

**Comment by gochev** [comment]
It looks this is broken again ?

**Comment by Vincent14** [comment]
Yes, same problem on Ubuntu 16.04

**Comment by DavidDudson** [comment]
16.04 fixed with adding 'DEBIAN_PREVENT_KEYBOARD_CHANGES=yes' to .zshenv

**Comment by jakehilton** [comment]
I'm seeing this issue with osx 10.12 when using pyenv. Not sure if it's zsh or something wonky with pyenv.

**Comment by mcornella** [comment]
Everybody who's having this problem, please test #5113.

**Comment by ttiurani** [comment]
So I struggled a bit with this, as vi-mode plugin broke. In fact, just `bindkey -v` breaks up and down keys, so I'm not sure if that's even by design. Anyway, after loading the vi-mode plugin, I just copy pasted from `lib/key-bindings.zsh` the following to my `.zshrc`:

```
# start typing + [Up-Arrow] - fuzzy find history forward
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
# start typing + [Down-Arrow] - fuzzy find history backward
if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi
```

and now up and down arrows work, and I have vi-mode enabled. #5113 did not fix this for me at least.

**Comment by waveform80** [comment]
Hmm, #5113 *did* fix this for me on Ubuntu 16.04 (whilst the `DEBIAN_PREVENT_KEYBOARD_CHANGES=yes` did not). I should also note, I've got the "safe-paste" plugin installed, which was the original cause of up-arrow failing to search the history in my case.

**Comment by NightMachinary** [comment]
On osx, @ttiurani 's solution is the only one that worked. vi-mode is enabled.

**Comment by Dwight-D** [comment]
Still having this issue in MacOS when using vi-mode.

In case @ttiurani 's solution doesn't work and you're in vi-mode you need to add `-M viins` to the command, like so:

`bindkey -M viins "${terminfo[kcuu1]}" up-line-or-beginning-search`

**Comment by busla** [comment]
> 'safe-paste' plugin workaround helped me on Ubuntu 13.04

this actually broke my history completion

**Comment by zmarffy** [comment]
20.04 is having the same issue but `safe-paste` fixes it there. Odd.
