### ISSUE TITLE
git completion not working in tmux

### ISSUE THREAD

**Issue by GriffinHeart** [robbyrussell/oh-my-zsh#3094]
Hello, I have a weird issue where git completion is working in iTerm but not inside a tmux session.

I have no idea how to debug this, but would like very much to make it work again.

````
~/src/discourse : orderable-user-bar : git co<tab>
co  -- alias for 'checkout'
commit  -- record changes to repository
commit-tree  -- create new commit object
compare  -- open GitHub compare view
config  -- get and set repository or global options
count-objects  -- count unpacked objects and display their disk consumption
````

then in tmux:
````
 ✘  ~/src/discourse   orderable-user-bar  tmux -u new -A -s default
 ~/src/discourse   orderable-user-bar  git co<tab>
CONTRIBUTING.md  COPYRIGHT.txt    config/          config.ru
````
when i press tab it shows the completion for list of files.

Plugins are still working in tmux, for example the `lol` plugin:

````
~/src/discourse   orderable-user-bar  invisible ~/.zshrc
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
DEFAULT_USER="griffin"
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git encode64 lol nyan yum)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
LANG=en_US.UTF-8
export EDITOR=vim
source /opt/boxen/env.sh
# makes terminal behave like vim
bindkey -e


alias ll="ls -lah"
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias zshrc="vim ~/.zshrc && reload"

#fixes C-s in mac os and some other bindings
stty start undef stop undef
stty -ixon -ixoff

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
DOCKER_HOST=tcp://localhost:4243

export JAVA_HOME="$(/usr/libexec/java_home)"
export EC2_AMITOOL_HOME="/opt/boxen/homebrew/Cellar/ec2-ami-tools/1.5.3/libexec"
export EC2_HOME="/opt/boxen/homebrew/Cellar/ec2-api-tools/1.7.1.0/libexec"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
````

and my `.tmux.conf`:

````
 ~/src/discourse   orderable-user-bar  cat ~/.tmux.conf
set -g default-shell /opt/boxen/homebrew/bin/zsh
set -g default-terminal "xterm-256color"
set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

set -g status-left-length 52
set -g status-right-length 451
set -g status-fg white
set -g status-bg colour234
set -g window-status-activity-attr bold
set -g pane-border-fg colour245
set -g pane-active-border-fg colour39
set -g message-fg colour16
set -g message-bg colour221
set -g message-attr bold
set -g status-left '#[fg=colour235,bg=colour252,bold] ❐ #S#[fg=colour252,bg=colour238,nobold]⮀#[fg=colour245,bg=colour238,bold] #(whoami)#[fg=colour238,bg=colour234,nobold]⮀'
set -g window-status-format "#[fg=white,bg=colour234] #I #W "
set -g window-status-current-format "#[fg=colour234,bg=colour39]⮀#[fg=colour25,bg=colour39,noreverse,bold] #I ⮁ #W#[fg=colour39,bg=colour234,nobold]⮀"

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
#bind-key -t vi-copy v begin-selection
#bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
#bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
set-option -g default-command "reattach-to-user-namespace -l zsh"
````

Any tips how to find the source of this issue?

**Comment by GriffinHeart** [comment]
@mcornella I'm sorry for late reply, with your comment I seem to have more information.

After trying to trigger git completion on each one:

terminal seems to work:
````
which _git
_git () {
	if (( CURRENT > 2 ))
	then
		local -a aliases
		local -A git_aliases
		aliases=(${(f)${${${(f)"$(_call_program aliases git config --get-regexp '\^alias\.')"}#alias.}/ /$'\n'}/(#e)/$'\n'}) 
...etc
````

using iTerm seems to work:
````
which _git
_git () {
	if (( CURRENT > 2 ))
	then
		local -a aliases
		local -A git_aliases
		aliases=(${(f)${${${(f)"$(_call_program aliases git config --get-regexp '\^alias\.')"}#alias.}/ /$'\n'}/(#e)/$'\n'})
...etc
````

but after launching a tmux session it doesn't seem to work:
````
 which _git
_git () {
        # undefined
        builtin autoload -XUz
}
````

Thanks for taking time.

**Comment by mcornella** [comment]
I've noticed you have 
```
set-option -g default-shell /opt/boxen/homebrew/bin/zsh
```
and
```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```
try changing that last "zsh" for the full path `/opt/boxen/homebrew/bin/zsh`. 
See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/21#issuecomment-39218614 for reference. 

Also I'm curious what `$SHELL` you have by default, run `echo $SHELL`.

**Comment by GriffinHeart** [comment]
@mcornella Thank you for your help, it seems this has been fixed

I don't know which of the following could've fixed it tho:

- Deleted my `.zcompdump` and regenerated it
- executed `unalias git`

After this it started working. I've also noticed that the `$fpath` variable was

outside tmux:
````
/Users/griffin/.oh-my-zsh/plugins/yum /Users/griffin/.oh-my-zsh/plugins/nyan /Users/griffin/.oh-my-zsh/plugins/lol /Users/griffin/.oh-my-zsh/plugins/encode64 /Users/griffin/.oh-my-zsh/plugins/git /Users/griffin/.oh-my-zsh/functions /Users/griffin/.oh-my-zsh/completions /opt/boxen/homebrew/share/zsh/site-functions /opt/boxen/homebrew/Cellar/zsh/5.0.5/share/zsh/functions
````

inside tmux:
````
/Users/griffin/.oh-my-zsh/plugins/yum /Users/griffin/.oh-my-zsh/plugins/nyan /Users/griffin/.oh-my-zsh/plugins/lol /Users/griffin/.oh-my-zsh/plugins/encode64 /Users/griffin/.oh-my-zsh/plugins/git /Users/griffin/.oh-my-zsh/functions /Users/griffin/.oh-my-zsh/completions /opt/boxen/homebrew/share/zsh/site-functions /usr/share/zsh/5.0.5/functions
````

notice the `/usr/share/zsh/5.0.5/functions`  vs `/opt/boxen/homebrew/Cellar/zsh/5.0.5/share/zsh/functions`

It is fixed now, but I thought i should put this information here in case one of it could be the cause

**Comment by mcornella** [comment]
Oh yes, that's pretty weird. Thankfully you managed to get it to work, cheers! 
Remember to close the issue :)

**Comment by MozMorris** [comment]
`unalias git` fixed it for me. I have it aliased to `hub`. What about you @GriffinHeart? 

Really I'd like to keep that alias in place.

**Comment by metcalfc** [comment]
@MozMorris 

Changing
```set-option -g default-command "reattach-to-user-namespace -l zsh" ```
to
```set-option -g default-command "reattach-to-user-namespace -l $SHELL"````

Fixed it for me with hub.

**Comment by MozMorris** [comment]
@metcalfc thanks but unfortunately that doesn't solve it for me.

**Comment by MozMorris** [comment]
Using the `github` plugin solved my problems.

**Comment by jersearls** [comment]
@metcalfc Thanks! `set-option -g default-command "reattach-to-user-namespace -l $SHELL"` fixed this issue for me.
