### ISSUE TITLE
compdef: unknown command or service: git

### ISSUE THREAD

**Issue by lostinplace** [robbyrussell/oh-my-zsh#3455]
This was previously referenced in #630 a solution was proposed here: https://github.com/robbyrussell/oh-my-zsh/issues/630#issuecomment-26227872  but the solution doesn't work

when .zshrc executes
````
source $ZSH/oh-my-zsh.sh
````

it fails to complete execution of the initialization, throws the error, and bloxks shell initialization, which prevents things like autocomplete

running
````
compaudit | sudo xargs chmod g-w
compaudit | sudo xargs chown root
rm ~/.zcompdump*
compinit
````

fails to fix the unsecure folders problem, and when I run compaudit I receive the following:
````
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.0.7/share/zsh/functions
/usr/local/share/zsh
/usr/local/Cellar/zsh/5.0.7/share/zsh
````
adding a call to compinit finishes the shell initialization (autocomplete works again), but I'd like to know how to fix the error output that appears on every terminal session load

for reference:  I'm using brew-installed zsh 5.0.7 (x86_64-apple-darwin13.4.0)

**Comment by dragon788** [comment]
@lostinplace Try the fix in this comment. https://github.com/robbyrussell/oh-my-zsh/issues/630#issuecomment-70291622

**Comment by lostinplace** [comment]
that improved a lot (now it's only one line)

now it's:

````
complete:13: command not found: compdef
````

**Comment by dragon788** [comment]
@lostinplace It sounds like it is trying to access an autocomplete word list but not finding it. What happens if you just run compaudit by itself? It should report the issues it finds. You can also try compinit by itself to see what it is complaining about.

**Comment by jmtatsch** [comment]
Related problem here. None of the mentioned fixes seem to work. 

zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y

**Comment by dragon788** [comment]
@jmtatsch Try running these commands, you can remove the # comments or just paste them in, your shell should ignore them and not try to run those lines.

#This will perform chmod g-w for each file returned by compaudit to remove write access for group
compaudit | xargs -I % chmod g-w "%"
#This will perform chown to current user (Windows and Linux) for each file returned by compaudit
compaudit | xargs -I % chown $USER "%"
#Remove all dump files (which normally speed up initialization)
rm ~/.zcompdump*
#Regenerate completions file
compinit

**Comment by jmtatsch** [comment]
Had to run this with sudo su, but it helped ;) Thank You

**Comment by lostinplace** [comment]
@dragon788 compaudit and compinit report nothing

output form new term is as follows:

````
Last login: Thu Jan 22 12:06:32 on ttys005
complete:13: command not found: compdef
Now using node v0.10.33
➜  ~
````

**Comment by dragon788** [comment]
@lostinplace what OS are you using this under? I've been using it on Cygwin, but I ran into a similar issue, it seems to have been fixed in the last month, so try upgrading your o-m-z.

**Comment by lostinplace** [comment]
I'm using OSX

**Comment by lostinplace** [comment]
I've also recently updated (in the past week)

**Comment by dragon788** [comment]
There are some notes about an entry importing ~/.profile possibly causing this message to show up. Check your .zshrc to see if it might be sourcing this file, as it was introduced in a prior version of oh-my-zsh.

**Comment by lostinplace** [comment]
I figured this out a little while ago, I had duplicated a call somewhere.  The problem is still occuring, but it's manageable

**Comment by emudojo** [comment]
at least for cygwin, the above did not work

**Comment by dragon788** [comment]
@emudojo Using regular Cygwin or preconfigured via Babun?

**Comment by emudojo** [comment]
regular old plain cygwin

**Comment by dragon788** [comment]
I've had to change the git setting in this git to get compinit and
compaudit and Git to quit fighting.
https://gist.github.com/dragon788/cba0c40f4983cd0b6a47 If that doesn't do
it, I'm wondering if its something in .zshrc or the .profile getting
sourced and failing.

**Comment by Honwhy** [comment]
use command
```
bash -x $ZSH/oh-my-zsh.sh
```
output:
```
{ ~ }  » bash -x $ZSH/oh-my-zsh.sh                                                              ~
+ '[' '' '!=' true ']'
+ env ZSH=/home/Honwhy/.oh-my-zsh DISABLE_UPDATE_PROMPT= zsh -f /home/Honwhy/.oh-my-zsh/tools/check_for_upgrade.sh
+ fpath=($ZSH/functions $ZSH/completions $fpath)
+ [[ -z '' ]]
+ ZSH_CUSTOM=/home/Honwhy/.oh-my-zsh/custom
+ [[ -z '' ]]
+ ZSH_CACHE_DIR=/home/Honwhy/.oh-my-zsh/cache/
/home/Honwhy/.oh-my-zsh/oh-my-zsh.sh: line 26: syntax error near unexpected token `('
/home/Honwhy/.oh-my-zsh/oh-my-zsh.sh: line 26: `for config_file ($ZSH/lib/*.zsh); do'

```
