### ISSUE TITLE
Android source code build commend "mm or mmm" couldn't use in oh-my-zsh

### ISSUE THREAD

**Issue by zh0122** [robbyrussell/oh-my-zsh#3882]
Hi, 
The commend mm/mmm can't use in oh-my-zsh.
It can use in bash.
If I execute below commend, `$ mmm -j16 -B frameworks/base/packages/SystemUI`
it will prompt `mmm:local:10: not valid in this context: -B` .

But `mmm -B frameworks/base/packages/SystemUI` or 
`mmm -j16 frameworks/base/packages/SystemUI` works normal in oh-my-zsh. 

The code of mmm is here. https://android.googlesource.com/platform/build/+/android-5.1.1_r2/envsetup.sh#725

Please check it . Thanks .

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

This seems like a Zsh issue to me. Have you tried to reproduce the behavior with vanilla Zsh? this should be as simple as temporarily removing your `~/.zshrc` and opening a new shell.

**Comment by zh0122** [comment]
Hi, 
Thanks for your replay. 

I tried it as you said. 
**It is a Zsh issue.**

But I can't find a way to report this issue to Zsh.
Could you help to report this issue to Zsh or tell me how to report this issue to Zsh? :)

Thanks a lot.

**Comment by mcornella** [comment]
Hi @zh0122, in my opinion this is a matter of that script not being cross-compatible between shells. I've downloaded and got the same result as you, so you should open a bug report to the Android team (not sure how to do that, google around).

FWIW, I'm currently dissecting that function to see where it fails.

**Comment by mcornella** [comment]
Found [this](http://nilvec.com/building-cyanogenmod-from-source.html): 

>If you use zsh envsetup.sh may fail, but you can simply
>
> ```sh
>   unsetopt NOMATCH
>```
> in your shell and you're good to go.

Try if it works, I can't check it without the full setup.

**Comment by mcornella** [comment]
Nope, I found the culprit. There's an issue within the script at [line 735](https://android.googlesource.com/platform/build/+/android-5.1.1_r2/envsetup.sh#735): 
```sh
local DASH_ARGS=$(echo "$@" | awk -v RS=" " -v ORS=" " '/^-.*$/')
```
This prints the arguments passed to `mmm()`, then passes that to awk to get only the parameters starting with a dash (`-`). Then, the output of that gets passed to the rest of the line, but notice there're no quotes around `$()` so this will fail.

So if you run
```sh
mmm -j16 -B frameworks/base/packages/SystemUI
```
this is the final `local` statement that gets run:
```sh
local 'DASH_ARGS=-j16' -B
``` 
which runs local with a `-B` argument. Since local doesn't accept parameters after the variable, zsh complains. A simple fix, wrapping the command within quotes:
```sh
local DASH_ARGS="$(echo "$@" | awk -v RS=" " -v ORS=" " '/^-.*$/')"
```

Anyway, this is clearly not an oh-my-zsh issue and I realise I've indulged you a bit too much, so if you can, please close this issue. Conversation will continue though

**Comment by mcornella** [comment]
FWIW, it does seem like a bug to me that zsh behaves differently here. 
Here's a comparison of what both do captured using debug mode in both bash and zsh (`set -xv`):

**bash:**
```bash
+ local 'DASH_ARGS=-j16 -B '
```
**zsh:**
```zsh
+mmm:10> local 'DASH_ARGS=-j16' -B
```
I think bash does the right thing here..

**Comment by ncanceill** [comment]
Yes, thanks @mcornella, the issue is with the Android script.

@zh0122 please close this issue.

**Comment by zh0122** [comment]
Hi, @mcornella 

I have followed your suggestion to add quotes in line735, **but it still not work**.

When I execute `mmm -j16 -B  packages/apps/LockClock`, it will show ``make: the `-j' option requires a positive integral argument``. 
![2](https://cloud.githubusercontent.com/assets/4396287/7592343/6666314a-f905-11e4-9792-74db78eb4b0c.png)

And when I execute `mmm -B -j16  packages/apps/LockClock`, it will show 
```
make: invalid option -- ' '
make: invalid option -- '-'
make: the `-j' option requires a positive integral argument
```
![3](https://cloud.githubusercontent.com/assets/4396287/7592388/99efb4fa-f905-11e4-9668-6e686a26cf1c.png)

**Both of the two commands can be executed in bash.**

Please help to check the result. :)
Do you have any other suggestions about this? 

Thanks

**Comment by KhasMek** [comment]
The android platform build env does not natively support building with shells other than bash. CyanogenMod has added _basic compatibility_ as shown by the following commits [0d8179e](https://github.com/CyanogenMod/android_build/commit/0d8179e), [e53c87d](https://github.com/CyanogenMod/android_build/commit/e53c87d), and [807976c](https://github.com/CyanogenMod/android_build/commit/807976c). Some functions are still unusable, clearly, as understood by the _basic compatibility_ commit. mka works fine for me in normal cases, and I so rarely use mmm. However, I have fixed the line in question thanks to @mcornella's previous research and is working fine on my end. Maybe you didn't fix the line fully or something? In any case- I have pushed a commit to cm's gerrit instance [here](http://review.cyanogenmod.org/#/c/98198/) if you would give it a test/review and we can move the discussion to it's proper location.

Nitpick- I think most people will assume you're building AOSP if you just state "android". Properly referencing the firmware you are actually building for (clearly you're building CM, or a CM based firmware, since you referenced LockClock), which has more support for the zsh shell may help a lot in future issue solving.

**Comment by zh0122** [comment]
Hi @KhasMek ,

I tried your patch in http://review.cyanogenmod.org/#/c/98198/1/envsetup.sh . It still does not work.

Both `mmm -j16 -B frameworks/base/packages/SystemUI` and `mmm -j16 -B frameworks/base/packages/SystemUI` could build, but neither of the param do not work.

When I execute `mmm -j16 -B frameworks/base/packages/SystemUI` and `mmm -j16 -B frameworks/base/packages/SystemUI`, however, it looks like the system execute `mmm frameworks/base/packages/SystemUI`.
So, I don't think your patch solve my issue. :) 
Do you have any other suggestions? 

Thanks for your help.

I build a CM base platform. 

Thanks.

**Comment by zh0122** [comment]
This issue is with AOSP. It has been moved to [Google code](https://code.google.com/p/android/issues/detail?id=174268&can=4&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars)
