### ISSUE TITLE
Git completion partly broken

### ISSUE THREAD

**Issue by nyddogghr** [robbyrussell/oh-my-zsh#4395]
Hi,

Firstly I don't know if the bug is specifically related to oh my zsh, but it started from my last update, so I'm posting here. Apologizes if it's not related.

So my issue is that since about a week, the completion for git checkout only works partially : for instance, if I use `gb <Tab>`, it shows the correct branches. But when I do `gco <Tab>`, it only shows a part of the branches names. Almost all of my branches are of the form `user/feature_or_fix/issue_number/name_of_the_branch`, and the completion only suggests the `name_of_the_branch` part of the branches. Here is an example : 
```
nyddogghr/feature/MEDIA-12/create_rails_5
```
`gb <Tab>` will show the full branch name, gut `gco <Tab>` will only show the `create_rails_5` part.
Of course, when selecting it it doesn't switch branch.

So is this an issue related to oh my zsh ? Does anyone else have this ?

Thanks for your help

**Comment by apjanke** [comment]
I'm on the current OMZ version on OS X 10.9.5. I can't reproduce. `gb <Tab>` and `gco <Tab>` both show me (local) branches with slashes in them. In addition, `gco <Tab>` will show remote branches with slashes in them.

```
[~/tmp/git-work on ⇄ master]
$ git branch nyddogghr/feature/MEDIA-12/create_rails_5
[~/tmp/git-work on ⇄ master]
$ gco
HEAD
master
nyddogghr/feature/MEDIA-12/create_rails_5
```

`gb` and `gco` are simple aliases in the `git` plugin. Maybe something's up with your completion as a result of #4383 / #3889. Are you seeing any other completion-related warnings or errors?

And what's your $fpath (`echo "${(F)fpath}"`)? Perhaps #3889 repaired some directory on your $fpath such that now it is included in your completions, whereas before it was silently ignored, and this is changing your completion behavior.

Have a look at `which _git`. It'll tell you what the completion definition is, even though it won't show you where it was loaded from.

I get this, in my working configuration:
```
$ which _git | shasum
3fe6d1b41bb1586e146f37c619f83ba484ee1981  -
```

**Comment by jwadolowski** [comment]
Hey @nyddogghr,

I was in the middle of writing exactly the same issue when I saw you've just posted that.

In my case it behaved pretty much the same 2 days ago (partial branch names), but now `git co <TAB>` shows me individual commits instead of branch names.

![git_oh-my-zsh](https://cloud.githubusercontent.com/assets/6334715/10068837/1efdb924-62a8-11e5-8304-2cdb758292fa.png)

Last week `git co <TAB>` definitely worked as expected and the only change I've recently made was `oh-my-zsh` update.

**Comment by nyddogghr** [comment]
Ok, I found the cause. From the issues you've linked, I found that removing `git-extras` plugin makes it work again. So yes it is related to OMZ, and more specifically to `git-extras`.
When removing it the branches are correctly found, but I still have extra branches (the `name_of_the_feature` part). `gco <tab>` will then show both `nyddogghr/feature/rails_5` and `rails_5`
But I don't have this issue if after having removed the plugin, I create a branch and then try to checkout. It seems to only be present for branch already existing.

I also don't have any issue with permissions, and here are the `$fpath` : 
```
/home/flof/.oh-my-zsh/plugins/history-substring-search
/home/flof/.oh-my-zsh/plugins/sudo
/home/flof/.oh-my-zsh/plugins/mvn
/home/flof/.oh-my-zsh/plugins/wd
/home/flof/.oh-my-zsh/plugins/systemd
/home/flof/.oh-my-zsh/plugins/nyan
/home/flof/.oh-my-zsh/plugins/chucknorris
/home/flof/.oh-my-zsh/plugins/common-aliases
/home/flof/.oh-my-zsh/plugins/archlinux
/home/flof/.oh-my-zsh/functions
/home/flof/.oh-my-zsh/completions
/home/flof/.oh-my-zsh/plugins/history-substring-search
/home/flof/.oh-my-zsh/plugins/sudo
/home/flof/.oh-my-zsh/plugins/mvn
/home/flof/.oh-my-zsh/plugins/wd
/home/flof/.oh-my-zsh/plugins/systemd
/home/flof/.oh-my-zsh/plugins/nyan
/home/flof/.oh-my-zsh/plugins/chucknorris
/home/flof/.oh-my-zsh/plugins/common-aliases
/home/flof/.oh-my-zsh/plugins/archlinux
/home/flof/.oh-my-zsh/plugins/git-remote-branch
/home/flof/.oh-my-zsh/plugins/git
/home/flof/.oh-my-zsh/plugins/git-extras
/home/flof/.oh-my-zsh/functions
/home/flof/.oh-my-zsh/completions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle

```
And the `which _git | shasum` : 
```
f7e81166870bbf091535cf666d510edd790f8828
```

**Comment by c0nscience** [comment]
I have the same issue since the last OMZ update a couple of days ago. I experience it with complex branchnames like ``feature/some_fancy_new_feature``. Before the last update it gets completed like a breeze, but now nothing happens.

**Comment by apjanke** [comment]
I can reproduce this if I run the `git-extras` plugin. With that, `gco <Tab>` only completes commit identifiers, not branch names.

Hmm. The `git-extras` plugin has not been changed in quite a while, so it wouldn't have been directly affected by the recent update.

```
[~/.oh-my-zsh on ⇄ master]
$ git log plugins/git-extras/git-extras.plugin.zsh | grep Date | head -5
Date:   Mon Dec 15 12:41:22 2014 +0800
Date:   Fri Jul 20 16:46:30 2012 +0200
Date:   Thu Jul 19 13:01:32 2012 +0200
```

Maybe this is the normal behavior of `git-extras`, and in your case, you had "insecure" permissions on its directory so it was being silently ignored and not actually running before, and then #3889 came along and fixed them and now `git-extras` is actually running.

Are there other features of `git-extras` which you *have* been using? (That will tell us if this scenario is likely, and also whether we can just ditch `git-extras` to resolve this.)

@nyddogghr: What system (OS, zsh, and git versions) are you on? And is that repo you're working on public, so we can try to reproduce the behavior with the exact same data set?

It's also weird that most of the OMZ plugin directories show up twice in your `$fpath`. That looks like what would happen if `~/.zshrc` was re-sourced in a running session, or a new `zsh -l` subshell was launched, possibly after the `git` plugins were removed from the list in `~/.zshrc`. Is that from a fresh terminal session? Re-running `~/.zshrc` doesn't update your session to the new configuration; you need to launch a completely fresh shell session.

**Comment by benjaoming** [comment]
I'm also experiencing this on the latest master branch. With git-extras. Switching it off fixes the issue.. but I'll miss git-extras.

No updates of zsh in trusty-backports since August 2014.

**Comment by benjaoming** [comment]
Reverting this commit makes everything work again:

https://github.com/robbyrussell/oh-my-zsh/commit/4bd6c43cfba17b6d13cd2f3b8f849ae3226e76e9

**Comment by apjanke** [comment]
This also seems to depend on the version of `zsh` I'm using. On OS X 10.9.5, with `zsh` 5.0.2, `gco` gives me commit IDs; with `zsh` 5.1.1, it gives me branch names.

```
[~/tmp/git-work on ⇄ master]
$ echo $ZSH_VERSION
5.0.2
[~/tmp/git-work on ⇄ master]
$ gco cc0af00
[✘ ~/tmp/git-work on ⇄ master]
$ /usr/local/bin/zsh -l
[~/tmp/git-work on ⇄ master]
$ echo $ZSH_VERSION
5.1.1
[~/tmp/git-work on ⇄ master]
$ gco
HEAD
master
nyddogghr/feature/MEDIA-12/create_rails_5
nyddogghr/feature/rails_5
```

Maybe `git-extras` is depending on the internals of `zsh`'s `_git` completion function, and the recent commit was written against a newer `zsh` that changed `_git`.

What `zsh` version(s) are you folks running?

**Comment by apjanke** [comment]
Oh, wait: it's not a zsh version difference. The difference for me is that my Homebrew-managed `zsh` uses `/usr/local/share/zsh/site-functions`, and I have a Homebrew-managed `git` installed, so it sees the `_git` completion provided by the `git` install instead of the one that comes with `zsh` itself.

**Comment by apjanke** [comment]
Think I found your problem. #3408 added an [override for `__git_commits`](https://github.com/spacewander/oh-my-zsh/blob/0c77e4ba6f52642d7f94e6cd72c869ad2e47c62f/plugins/git-extras/git-extras.plugin.zsh#L34-L43).

```
__git_commits() {
    declare -A commits
    git log --oneline -15 | sed 's/\([[:alnum:]]\{7\}\) /\1:/' | while read commit
    do
        hash=$(echo $commit | cut -d':' -f1)
        commits[$hash]="$commit"
    done
    local ret=1
    _describe -t commits commit commits && ret=0
}
```

This is rather different from the `zsh` `_git`'s `__git_commits()`, which, despite its name, returns branch names if available, and not just commit identifiers.

```
__git_commits () {
  # TODO: deal with things that __git_heads and __git_tags has in common (i.e.,
  # if both exists, they need to be completed to heads/x and tags/x.
  _alternative \
    'heads::__git_heads' \
    'commit-tags::__git_commit_tags' \
    'commit-objects::__git_commit_objects'
}
```

**Comment by apjanke** [comment]
Made a fix: #4444

**Comment by benjaoming** [comment]
Hoping the fix will find its way soon :)

Another problem has been that `gco <filename>` has stopped working.

**Comment by apjanke** [comment]
`gco <filename>` is also fixed in #4444. Just note that only modified files are presented as completion options, so if you're testing it, make sure you have some modified files in your repo that `gco` would actualy do something to.

**Comment by benjaoming** [comment]
@apjanke yup I know :) I knew this auto completion very much in the back of my head / eyes closed / in my sleep.... when it was gone, the world started feeling strange and unfamiliar :D

**Comment by apjanke** [comment]
This `git-extras` stuff is pretty neat. Thanks for introducing me to it; sorry it had to be by way of it breaking.

**Comment by benjaoming** [comment]
Yeah, `git-extras` is awesome... I use `git delete-branch` all the time.

**Comment by peygar** [comment]
Hey I'm still having the problem where gco <Tab> shows me commit names as well as branch names. Any way to turn this off? I'm on zsh 5.2
