### ISSUE TITLE
_values:compvalues:10: not enough arguments

### ISSUE THREAD

**Issue by wess** [robbyrussell/oh-my-zsh#6934]
Starting to see this error again, haven't seen it since 2014. It happens any time I try to tab complete a path inline with a command. I updated this morning and just started seeing it.

```
➜  modok swift run Packages/
_values:compvalues:10: not enough arguments
_values:compvalues:10: not enough arguments
_values:compvalues:10: not enough arguments
➜  modok swift run Packages/
```

**Comment by mcornella** [comment]
Try deleting the completion cache with `rm ~/.zcompdump*`.

**Comment by ksakiyama** [comment]
I have a same problem.
I tried `rm ~/.zcompdump*`, but the problem was not resolved...

**Comment by mcornella** [comment]
Does this happen with any command that completes a path? Generate a trace of the completion function by typing the command that fails to complete, then pressing `CTRL`+`X`, `?`. Follow the instructions shown and post the trace file.

**Comment by ksakiyama** [comment]
Thanks for your comment.
I reinstalled oh-my-zsh after that time. And the problem was resolved!

**Comment by stefanlesser** [comment]
I had the same issue and found this discussion. Here's the trace:
[zsh.log](https://github.com/robbyrussell/oh-my-zsh/files/2193636/zsh.log)

Deleting the completion cache didn't help. Here's another trace just after I deleted it:
[zsh2.log](https://github.com/robbyrussell/oh-my-zsh/files/2193646/zsh2.log)

**Comment by mcornella** [comment]
It's possible that you're using an openstack version not compatible with the version of the completion file bundled with your zsh version (5.3). Try using the [latest version of zsh's _openstack](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_openstack).

Here's the relevant part of the trace:
```
     +_openstack:183> _values -w option
      +_values:3> local subopts opt usecc garbage
      +_values:5> subopts=( ) 
      +_values:6> zparseopts -D -a garbage 'C=usecc' 'O:=subopts' M: J: V: 1 2 n F: X:
      +_values:8> ((  0  ))
      +_values:10> compvalues -i -w option
_values:compvalues:10: not enough arguments
```

The same can be said of OP @wess: an outdated completion file might be the culprit.

**Comment by wess** [comment]
cleaned up the outdated, and fixed things right up, appreciate the help!

**Comment by amadeu01** [comment]
I still having the problem, I could not fix it by uninstall/reinstall oh-my-zsh.
Does anyone know how to fix it?

**Comment by amadeu01** [comment]
Seems to be related to https://www.zsh.org/mla/workers/2017/msg00183.html

**Comment by zhuxiaoxi** [comment]
@amadeu01 I'm having the same problem. Have you found a solution?

**Comment by amadeu01** [comment]
> @amadeu01 I'm having the same problem. Have you found a solution?

I'm no longer facing the problem, however I cannot recall what I did :( sorry!

**Comment by skagedal** [comment]
I am facing this same problem. I want `swift` to auto-complete to Apple's Swift, not the openstack stuff, and I'm getting the "compvalues" error.

I'm using macOS 10.14.5, system `zsh` which is `zsh 5.3 (x86_64-apple-darwin18.0)`, freshly upgrade `oh-my-zsh` (currently at commit `1343ab67`).

The Swift PM comes with a [completion script generator](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#shell-completion-scripts), and this also seems to be bundled with `oh-my-zsh` as part of the `swiftpm` plugin. Enabling this plugin does not help. 

The [Zsh mailing list message](https://www.zsh.org/mla/workers/2017/msg00183.html) mentioned above talks about a solution:

> Probably the right thing is to add _swift, and use _pick_variant to choose whether to call _openstack or to complete Apple's compiler options.

Has this been implemented? Are there any workarounds? Like, can I disable the `_openstack` thing somehow? 

Here's my `swift C-x ?` output.

<details>
<summary>Output of trace</summary>
<pre>
+_complete_debug:20> : zsh 5.3
+_complete_debug:21> _main_complete
+_main_complete:11> local IFS=$' \t\n\C-@'
+_main_complete:25> eval $'local -A _comp_caller_options;\n             _comp_caller_options=(${(kv)options[@]});\n             setopt localoptions localtraps localpatterns ${_comp_options[@]};\n             local IFS=$\' \t\r\n\0\';\n             builtin enable -p \| \~ \( \? \* \[ \< \^ \# 2>/dev/null;\n             exec </dev/null;\n             trap - ZERR;\n             local -a reply;\n             local REPLY'
 +(eval):1> local -A _comp_caller_options
 +(eval):2> _comp_caller_options=( posixargzero off autolist on printexitvalue off kshzerosubscript off histreduceblanks off chaselinks off extendedglob on localloops off histnostore off automenu on globcomplete off unset on listpacked off promptsubst on shwordsplit off pathdirs off kshtypeset off listtypes on warncreateglobal off promptbang off dotglob off braceexpand on listbeep on correctall off privileged off numericglobsort off histverify on trackall on histsubstpattern off globstarshort off cbases off rcquotes off posixaliases off histfindnodups off bashautolist off sharehistory on overstrike off kshautoload off incappendhistory on appendcreate off promptcr on mailwarn off pushdignoredups on interactive on ignoreeof off globsubst off rematchpcre off monitor on histsavebycopy on histbeep on debugbeforecmd on magicequalsubst off rmstarsilent off posixjobs off hashcmds on posixtraps off extendedhistory on notify on kshoptionprint off histexpiredupsfirst on glob on posixcd off braceccl off badpattern on longlistjobs on banghist on dvorak off alwaystoend on hashall on globalexport on ksharrays off correct off autonamedirs off histexpand on typesetsilent off rmstarwait off histnofunctions off autoparamslash on trapsasync off sunkeyboardhack off promptsp on histsavenodups off autocd on allexport off posixidentifiers off cshjunkiehistory off autopushd on completeinword on completealiases off aliases off autocontinue off appendhistory on singlelinezle off hashlistall on ignoreclosebraces off recexact off localoptions on interactivecomments on errexit off cshjunkiequotes off markdirs off hashdirs on cdablevars off rcexpandparam on vi off printeightbit off multifuncdef on xtrace on login on cshjunkieloops off histappend on histignorespace on evallineno on shfileexpansion off rcs on functionargzero on errreturn off combiningchars on histignoredups on histfcntllock off beep on autoremoveslash on hup on globdots off autoparamkeys on shnullcmd off multibyte on zle on promptpercent on flowcontrol off continueonerror off incappendhistorytime off autoresume off globassign off caseglob on shortloops on bsdecho off cprecedences off log on transientrprompt off verbose off localpatterns on ignorebraces off pipefail off equals on menucomplete off cshnullglob off casematch on promptvars on histallowclobber off bareglobqual on shinstdin on restricted off pushdminus on nullglob on chasedots off mailwarning off listambiguous on cshnullcmd off bashrematch off octalzeroes off forcefloat off exec on multios on emacs off nomatch on pathscript off localtraps on stdin on onecmd off kshglob off clobber on posixbuiltins off alwayslastprompt on pushdtohome off histignorealldups off hashexecutablesonly off pushdsilent off shoptionletters off physical off sourcetrace off histlexwords off bgnice on globalrcs on posixstrings off checkjobs on shglob off singlecommand off listrowsfirst off ) 
 +(eval):3> setopt localoptions localtraps localpatterns bareglobqual extendedglob glob multibyte multifuncdef nullglob rcexpandparam unset NO_allexport NO_aliases NO_cshnullglob NO_cshjunkiequotes NO_errexit NO_globassign NO_globsubst NO_histsubstpattern NO_ignorebraces NO_ignoreclosebraces NO_kshglob NO_ksharrays NO_kshtypeset NO_markdirs NO_octalzeroes NO_posixbuiltins NO_shwordsplit NO_shglob NO_warncreateglobal
 +(eval):4> local IFS=$' \t\C-M\n\C-@'
 +(eval):5> enable -p '|' '~' '(' '?' '*' '[' '<' '^' '#'
 +(eval):7> trap - ZERR
 +(eval):8> local -a reply
 +(eval):9> local REPLY
+_main_complete:27> local func funcs ret=1 tmp _compskip format nm call match min max i num _completers _completer _completer_num curtag _comp_force_list _matchers _matcher _c_matcher _matcher_num _comp_tags _comp_mesg mesg str context state state_descr line opt_args val_args curcontext='' _last_nmatches=-1 _last_menu_style _def_menu_style _menu_style sel _tags_level=0 _saved_exact='' _saved_lastprompt=yes _saved_list=ambiguous _saved_insert=automenu-unambiguous _saved_colors='' _saved_colors_set=1 _ambiguous_color=''
+_main_complete:42> local _comp_priv_prefix
+_main_complete:43> unset _comp_priv_prefix
+_main_complete:46> local -a precommands
+_main_complete:48> typeset -U _lastdescr _comp_ignore _comp_colors
+_main_complete:52> [[ -z '' ]]
+_main_complete:52> curcontext=::: 
+_main_complete:54> zstyle -s :completion::::: insert-tab tmp
+_main_complete:54> tmp=yes 
+_main_complete:56> [[ yes = *pending(|[[:blank:]]*) || yes = *pending=(#b)([0-9]##)(|[[:blank:]]*) ]]
+_main_complete:64> [[ automenu-unambiguous = tab* ]]
+_main_complete:77> [[ '' = \* ]]
+_main_complete:87> [[ -z '' ]]
+_main_complete:88> [[ -o equals ]]
+_main_complete:88> compset -P 1 '='
+_main_complete:90> [[ '' != */* && '' = \~ ]]
+_main_complete:98> _setup default
 +_setup:3> local val nm=0
 +_setup:5> [[ 1 -eq 1 ]]
 +_setup:5> 2=default 
 +_setup:7> zstyle -a :completion:::::default list-colors val
 +_setup:8> zmodload -i zsh/complist
 +_setup:9> [[ default = default ]]
 +_setup:10> _comp_colors=( '' ) 
 +_setup:27> zstyle -s :completion:::::default show-ambiguity val
 +_setup:32> zstyle -t :completion:::::default list-packed
 +_setup:34> [[ 2 -eq 1 ]]
 +_setup:37> compstate[list]=ambiguous 
 +_setup:40> zstyle -t :completion:::::default list-rows-first
 +_setup:42> [[ 2 -eq 1 ]]
 +_setup:45> compstate[list]=ambiguous 
 +_setup:48> zstyle -t :completion:::::default last-prompt
 +_setup:50> [[ 2 -eq 1 ]]
 +_setup:53> compstate[last_prompt]=yes 
 +_setup:56> zstyle -t :completion:::::default accept-exact
 +_setup:58> [[ 2 -eq 1 ]]
 +_setup:61> compstate[exact]='' 
 +_setup:64> [[ _last_nmatches -ge 0 ]]
 +_setup:67> zstyle -a :completion:::::default menu val
 +_setup:68> _last_nmatches=0 
 +_setup:69> _last_menu_style=( select ) 
 +_setup:74> [[ '' != always ]]
 +_setup:75> zstyle -s :completion:::::default force-list val
+_main_complete:99> _def_menu_style=( select ) 
+_main_complete:108> _last_menu_style=( ) 
+_main_complete:110> zstyle -s :completion:::::default list-prompt tmp
+_main_complete:114> zstyle -s :completion:::::default select-prompt tmp
+_main_complete:118> zstyle -s :completion:::::default select-scroll tmp
+_main_complete:125> ((  0  ))
+_main_complete:137> zstyle -a :completion::::: completer _completers
+_main_complete:138> _completers=( _complete _ignored ) 
+_main_complete:143> _completer_num=1 
+_main_complete:146> integer SECONDS=0
+_main_complete:160> funcs=( ) 
+_main_complete:161> compprefuncs=( ) 
+_main_complete:166> tmp=_complete
+_main_complete:168> [[ -n '' ]]
+_main_complete:170> [[ _complete = *:-* ]]
+_main_complete:173> [[ _complete = *:* ]]
+_main_complete:177> _completer=complete 
+_main_complete:180> curcontext=:complete:: 
+_main_complete:181> zstyle -t :completion::complete::: show-completer
+_main_complete:184> zstyle -a :completion::complete::: matcher-list _matchers
+_main_complete:187> _matcher_num=1 
+_main_complete:188> _matcher='' 
+_main_complete:189> _c_matcher=m:{a-zA-Z}={A-Za-z}
+_main_complete:190> [[ 'm:{a-zA-Z}={A-Za-z}' == +* ]]
+_main_complete:193> _matcher='m:{a-zA-Z}={A-Za-z}' 
+_main_complete:196> _comp_mesg='' 
+_main_complete:197> [[ -n '' ]]
+_main_complete:202> _complete
 +_complete:7> local comp name oldcontext ret=1 service
 +_complete:8> typeset -T curcontext=:complete:: ccarray
 +_complete:10> oldcontext=:complete:: 
 +_complete:14> [[ -n '' ]]
 +_complete:96> comp=_first 
 +_complete:97> [[ -n _first ]]
 +_complete:98> service=-first- 
 +_complete:99> ccarray[3]=-first- 
 +_complete:100> eval _first
  +(eval):1> _first
 +_complete:100> ret=0 
 +_complete:101> [[ '' = all ]]
 +_complete:110> [[ -n '' ]]
 +_complete:114> ret=1 
 +_complete:115> [[ command = command ]]
 +_complete:116> curcontext=:complete:: 
 +_complete:117> _normal -s
  +_normal:3> local _comp_command1 _comp_command2 _comp_command skip
  +_normal:5> [[ -s = -s ]]
  +_normal:6> skip=( -s ) 
  +_normal:16> [[ -o BANG_HIST && '' = !*: || '' = "!*: ]]
  +_normal:29> [[ CURRENT -eq 1 ]]
  +_normal:38> _set_command
   +_set_command:6> local command
   +_set_command:8> command=swift 
   +_set_command:10> [[ -z swift ]]
   +_set_command:12> ((  0 + 0  ))
   +_set_command:15> [[ s = \= ]]
   +_set_command:19> [[ swift = ..#/* ]]
   +_set_command:23> [[ swift = */* ]]
   +_set_command:28> _comp_command1=swift 
   +_set_command:29> _comp_command2=/usr/bin/swift 
   +_set_command:30> _comp_command=swift 
  +_normal:40> _dispatch -s swift swift /usr/bin/swift -default-
   +_dispatch:3> local comp pat val name i ret=1 _compskip=''
   +_dispatch:4> local curcontext=:complete:: service str noskip
   +_dispatch:5> local -a match mbegin mend
   +_dispatch:9> [[ -s = -s ]]
   +_dispatch:10> noskip=yes 
   +_dispatch:11> shift
   +_dispatch:14> [[ -z yes ]]
   +_dispatch:16> curcontext=:complete:swift: 
   +_dispatch:18> shift
   +_dispatch:22> [[ '' != (all|*patterns*) ]]
   +_dispatch:24> str=swift
   +_dispatch:25> [[ -n swift ]]
   +_dispatch:26> service=swift 
   +_dispatch:24> str=/usr/bin/swift
   +_dispatch:25> [[ -n /usr/bin/swift ]]
   +_dispatch:26> service=/usr/bin/swift 
   +_dispatch:24> str=-default-
   +_dispatch:25> [[ -n -default- ]]
   +_dispatch:26> service=-default- 
   +_dispatch:45> ret=1 
   +_dispatch:46> str=swift
   +_dispatch:47> [[ -n swift ]]
   +_dispatch:51> str=swift 
   +_dispatch:52> name=swift 
   +_dispatch:53> comp=_openstack 
   +_dispatch:54> service=swift 
   +_dispatch:56> [[ -z _openstack ]]
   +_dispatch:56> break
   +_dispatch:61> [[ -n _openstack && swift != -default- ]]
   +_dispatch:62> _compskip=patterns 
   +_dispatch:63> eval _openstack
    +(eval):1> _openstack
     +_openstack:6> local curcontext=:complete:swift: state line expl ret=1
     +_openstack:8> local -a clnts_compl_new clnts_compl_old clnts_swift_like
     +_openstack:26> clnts_compl_new=( aodh barbican designate gnocchi openstack ) 
     +_openstack:27> clnts_compl_old=( ceilometer cinder cloudkitty glance heat ironic keystone magnum manila mistral monasca murano neutron nova sahara senlin trove ) 
     +_openstack:28> clnts_swift_like=( swift ) 
     +_openstack:32> ((  ! 1  ))
     +_openstack:41> local -a conn_opts
     +_openstack:42> local opt arg word
     +_openstack:44> [[ swift == openstack ]]
     +_openstack:59> [[ -n '' ]]
     +_openstack:124> [[ -n '' ]]
     +_openstack:161> [[ -n swift ]]
     +_openstack:162> [[ -z '' ]]
     +_openstack:164> _cache_openstack_clnt_outputs[$service]=     +_openstack:164> swift --help
     +_openstack:164> _cache_openstack_clnt_outputs[$service]=$'OVERVIEW: Swift compiler\n\nUSAGE: swift [options] <inputs>\n\nOPTIONS:\n  -assert-config <value>  Specify the assert_configuration replacement. Possible values are Debug, Release, Unchecked, DisableReplacement.\n  -continue-building-after-errors\n                          Continue building, even after errors are encountered\n  -debug-info-format=<value>\n                          Specify the debug info format type to either \'dwarf\' or \'codeview\'\n  -debug-info-store-invocation\n                          Emit the compiler invocation in the debug info.\n  -debug-prefix-map <value>\n                          Remap source paths in debug info\n  -D <value>              Marks a conditional compilation flag as true\n  -enforce-exclusivity=<enforcement>\n                          Enforce law of exclusivity\n  -framework <value>      Specifies a framework which should be linked against\n  -Fsystem <value>        Add directory to system framework search path\n  -F <value>              Add directory to framework search path\n  -gdwarf-types           Emit full DWARF type info.\n  -gline-tables-only      Emit minimal debug info for backtraces only\n  -gnone                  Don\'t emit debug info\n  -g                      Emit debug info. This is the preferred setting for debugging with LLDB.\n  -help                   Display available options\n  -index-store-path <path>\n                          Store indexing data to <path>\n  -I <value>              Add directory to the import search path\n  -j <n>                  Number of commands to execute in parallel\n  -L <value>              Add directory to library link search path\n  -l<value>               Specifies a library which should be linked against\n  -module-cache-path <value>\n                          Specifies the Clang module cache path\n  -module-link-name <value>\n                          Library to link against when using this module\n  -module-name <value>    Name of the module to build\n  -nostdimport            Don\'t search the standard library import path for modules\n  -num-threads <n>        Enable multi-threading and specify number of threads\n  -Onone                  Compile without any optimization\n  -Osize                  Compile with optimizations and target small code size\n  -Ounchecked             Compile with optimizations and remove runtime safety checks\n  -O                      Compile with optimizations\n  -remove-runtime-asserts Remove runtime safety checks.\n  -Rpass-missed=<value>   Report missed transformations by optimization passes whose name matches the given POSIX regular expression\n  -Rpass=<value>          Report performed transformations by optimization passes whose name matches the given POSIX regular expression\n  -save-optimization-record-path <value>\n                          Specify the file name of any generated YAML optimization record\n  -save-optimization-record\n                          Generate a YAML optimization record file\n  -sdk <sdk>              Compile against <sdk>\n  -static-executable      Statically link the executable\n  -static-stdlib          Statically link the Swift standard library\n  -suppress-warnings      Suppress all warnings\n  -swift-version <vers>   Interpret input according to a specific Swift language version number\n  -target-cpu <value>     Generate code for a particular CPU variant\n  -target-variant <value> Generate code that may run on a particular variant of the  deployment target\n  -target <value>         Generate code for the given target\n  -use-ld=<value>         Specifies the linker to be used\n  -version                Print version information and exit\n  -vfsoverlay <value>     Add directory to VFS overlay file\n  -v                      Show commands to run and use verbose output\n  -warn-implicit-overrides\n                          Warn about implicit overrides of protocol members\n  -warn-swift3-objc-inference-complete\n                          Warn about deprecated @objc inference in Swift 3 for every declaration that will no longer be inferred as @objc in Swift 4\n  -warn-swift3-objc-inference-minimal\n                          Warn about deprecated @objc inference in Swift 3 based on direct uses of the Objective-C entrypoint\n  -warnings-as-errors     Treat warnings as errors\n  -working-directory <path>\n                          Resolve file paths relative to the specified directory\n  -Xcc <arg>              Pass <arg> to the C/C++/Objective-C compiler\n  -Xlinker <value>        Specifies an option which should be passed to the linker' 
     +_openstack:165> _cache_openstack_clnt_opts[$service]='-assert-config -continue-building-after-errors -debug-info-format -debug-info-store-invocation -debug-prefix-map -D -enforce-exclusivity -framework -Fsystem -F -gdwarf-types -gline-tables-only -gnone -g -help -index-store-path -I -j -L -l<value> -module-cache-path -module-link-name -module-name -nostdimport -num-threads -Onone -Osize -Ounchecked -O -remove-runtime-asserts -Rpass-missed -Rpass -save-optimization-record-path -save-optimization-record -sdk -static-executable -static-stdlib -suppress-warnings -swift-version -target-cpu -target-variant -target -use-ld -version -vfsoverlay -v -warn-implicit-overrides -warn-swift3-objc-inference-complete -warn-swift3-objc-inference-minimal -warnings-as-errors -working-directory -Xcc -Xlinker' 
     +_openstack:166> _cache_openstack_clnt_cmds[$service]='' 
     +_openstack:168> local cmd
     +_openstack:175> [[ -n '' ]]
     +_openstack:179> [[ -z '' && '' == -* ]]
     +_openstack:182> [[ -z '' ]]
     +_openstack:183> _values -w option
      +_values:3> local subopts opt usecc garbage
      +_values:5> subopts=( ) 
      +_values:6> zparseopts -D -a garbage 'C=usecc' 'O:=subopts' M: J: V: 1 2 n F: X:
      +_values:8> ((  0  ))
      +_values:10> compvalues -i -w option
_values:compvalues:10: not enough arguments
      +_values:156> curcontext=:complete:: 
      +_values:158> return 1
     +_openstack:192> return ret
   +_dispatch:64> [[ patterns = (all|*patterns*) ]]
   +_dispatch:64> return ret
 +_complete:142> _compskip='' 
 +_complete:144> return ret
+_main_complete:206> ((  _matcher_num++  ))
+_main_complete:189> _c_matcher=r:|=*
+_main_complete:190> [[ 'r:|=*' == +* ]]
+_main_complete:193> _matcher='r:|=*' 
+_main_complete:196> _comp_mesg='' 
+_main_complete:197> [[ -n '' ]]
+_main_complete:202> _complete
 +_complete:7> local comp name oldcontext ret=1 service
 +_complete:8> typeset -T curcontext=:complete:: ccarray
 +_complete:10> oldcontext=:complete:: 
 +_complete:14> [[ -n '' ]]
 +_complete:96> comp=_first 
 +_complete:97> [[ -n _first ]]
 +_complete:98> service=-first- 
 +_complete:99> ccarray[3]=-first- 
 +_complete:100> eval _first
  +(eval):1> _first
 +_complete:100> ret=0 
 +_complete:101> [[ '' = all ]]
 +_complete:110> [[ -n '' ]]
 +_complete:114> ret=1 
 +_complete:115> [[ command = command ]]
 +_complete:116> curcontext=:complete:: 
 +_complete:117> _normal -s
  +_normal:3> local _comp_command1 _comp_command2 _comp_command skip
  +_normal:5> [[ -s = -s ]]
  +_normal:6> skip=( -s ) 
  +_normal:16> [[ -o BANG_HIST && '' = !*: || '' = "!*: ]]
  +_normal:29> [[ CURRENT -eq 1 ]]
  +_normal:38> _set_command
   +_set_command:6> local command
   +_set_command:8> command=swift 
   +_set_command:10> [[ -z swift ]]
   +_set_command:12> ((  0 + 0  ))
   +_set_command:15> [[ s = \= ]]
   +_set_command:19> [[ swift = ..#/* ]]
   +_set_command:23> [[ swift = */* ]]
   +_set_command:28> _comp_command1=swift 
   +_set_command:29> _comp_command2=/usr/bin/swift 
   +_set_command:30> _comp_command=swift 
  +_normal:40> _dispatch -s swift swift /usr/bin/swift -default-
   +_dispatch:3> local comp pat val name i ret=1 _compskip=''
   +_dispatch:4> local curcontext=:complete:: service str noskip
   +_dispatch:5> local -a match mbegin mend
   +_dispatch:9> [[ -s = -s ]]
   +_dispatch:10> noskip=yes 
   +_dispatch:11> shift
   +_dispatch:14> [[ -z yes ]]
   +_dispatch:16> curcontext=:complete:swift: 
   +_dispatch:18> shift
   +_dispatch:22> [[ '' != (all|*patterns*) ]]
   +_dispatch:24> str=swift
   +_dispatch:25> [[ -n swift ]]
   +_dispatch:26> service=swift 
   +_dispatch:24> str=/usr/bin/swift
   +_dispatch:25> [[ -n /usr/bin/swift ]]
   +_dispatch:26> service=/usr/bin/swift 
   +_dispatch:24> str=-default-
   +_dispatch:25> [[ -n -default- ]]
   +_dispatch:26> service=-default- 
   +_dispatch:45> ret=1 
   +_dispatch:46> str=swift
   +_dispatch:47> [[ -n swift ]]
   +_dispatch:51> str=swift 
   +_dispatch:52> name=swift 
   +_dispatch:53> comp=_openstack 
   +_dispatch:54> service=swift 
   +_dispatch:56> [[ -z _openstack ]]
   +_dispatch:56> break
   +_dispatch:61> [[ -n _openstack && swift != -default- ]]
   +_dispatch:62> _compskip=patterns 
   +_dispatch:63> eval _openstack
    +(eval):1> _openstack
     +_openstack:6> local curcontext=:complete:swift: state line expl ret=1
     +_openstack:8> local -a clnts_compl_new clnts_compl_old clnts_swift_like
     +_openstack:26> clnts_compl_new=( aodh barbican designate gnocchi openstack ) 
     +_openstack:27> clnts_compl_old=( ceilometer cinder cloudkitty glance heat ironic keystone magnum manila mistral monasca murano neutron nova sahara senlin trove ) 
     +_openstack:28> clnts_swift_like=( swift ) 
     +_openstack:32> ((  ! 1  ))
     +_openstack:41> local -a conn_opts
     +_openstack:42> local opt arg word
     +_openstack:44> [[ swift == openstack ]]
     +_openstack:59> [[ -n '' ]]
     +_openstack:124> [[ -n '' ]]
     +_openstack:161> [[ -n swift ]]
     +_openstack:162> [[ -z '' ]]
     +_openstack:164> _cache_openstack_clnt_outputs[$service]=     +_openstack:164> swift --help
     +_openstack:164> _cache_openstack_clnt_outputs[$service]=$'OVERVIEW: Swift compiler\n\nUSAGE: swift [options] <inputs>\n\nOPTIONS:\n  -assert-config <value>  Specify the assert_configuration replacement. Possible values are Debug, Release, Unchecked, DisableReplacement.\n  -continue-building-after-errors\n                          Continue building, even after errors are encountered\n  -debug-info-format=<value>\n                          Specify the debug info format type to either \'dwarf\' or \'codeview\'\n  -debug-info-store-invocation\n                          Emit the compiler invocation in the debug info.\n  -debug-prefix-map <value>\n                          Remap source paths in debug info\n  -D <value>              Marks a conditional compilation flag as true\n  -enforce-exclusivity=<enforcement>\n                          Enforce law of exclusivity\n  -framework <value>      Specifies a framework which should be linked against\n  -Fsystem <value>        Add directory to system framework search path\n  -F <value>              Add directory to framework search path\n  -gdwarf-types           Emit full DWARF type info.\n  -gline-tables-only      Emit minimal debug info for backtraces only\n  -gnone                  Don\'t emit debug info\n  -g                      Emit debug info. This is the preferred setting for debugging with LLDB.\n  -help                   Display available options\n  -index-store-path <path>\n                          Store indexing data to <path>\n  -I <value>              Add directory to the import search path\n  -j <n>                  Number of commands to execute in parallel\n  -L <value>              Add directory to library link search path\n  -l<value>               Specifies a library which should be linked against\n  -module-cache-path <value>\n                          Specifies the Clang module cache path\n  -module-link-name <value>\n                          Library to link against when using this module\n  -module-name <value>    Name of the module to build\n  -nostdimport            Don\'t search the standard library import path for modules\n  -num-threads <n>        Enable multi-threading and specify number of threads\n  -Onone                  Compile without any optimization\n  -Osize                  Compile with optimizations and target small code size\n  -Ounchecked             Compile with optimizations and remove runtime safety checks\n  -O                      Compile with optimizations\n  -remove-runtime-asserts Remove runtime safety checks.\n  -Rpass-missed=<value>   Report missed transformations by optimization passes whose name matches the given POSIX regular expression\n  -Rpass=<value>          Report performed transformations by optimization passes whose name matches the given POSIX regular expression\n  -save-optimization-record-path <value>\n                          Specify the file name of any generated YAML optimization record\n  -save-optimization-record\n                          Generate a YAML optimization record file\n  -sdk <sdk>              Compile against <sdk>\n  -static-executable      Statically link the executable\n  -static-stdlib          Statically link the Swift standard library\n  -suppress-warnings      Suppress all warnings\n  -swift-version <vers>   Interpret input according to a specific Swift language version number\n  -target-cpu <value>     Generate code for a particular CPU variant\n  -target-variant <value> Generate code that may run on a particular variant of the  deployment target\n  -target <value>         Generate code for the given target\n  -use-ld=<value>         Specifies the linker to be used\n  -version                Print version information and exit\n  -vfsoverlay <value>     Add directory to VFS overlay file\n  -v                      Show commands to run and use verbose output\n  -warn-implicit-overrides\n                          Warn about implicit overrides of protocol members\n  -warn-swift3-objc-inference-complete\n                          Warn about deprecated @objc inference in Swift 3 for every declaration that will no longer be inferred as @objc in Swift 4\n  -warn-swift3-objc-inference-minimal\n                          Warn about deprecated @objc inference in Swift 3 based on direct uses of the Objective-C entrypoint\n  -warnings-as-errors     Treat warnings as errors\n  -working-directory <path>\n                          Resolve file paths relative to the specified directory\n  -Xcc <arg>              Pass <arg> to the C/C++/Objective-C compiler\n  -Xlinker <value>        Specifies an option which should be passed to the linker' 
     +_openstack:165> _cache_openstack_clnt_opts[$service]='-assert-config -continue-building-after-errors -debug-info-format -debug-info-store-invocation -debug-prefix-map -D -enforce-exclusivity -framework -Fsystem -F -gdwarf-types -gline-tables-only -gnone -g -help -index-store-path -I -j -L -l<value> -module-cache-path -module-link-name -module-name -nostdimport -num-threads -Onone -Osize -Ounchecked -O -remove-runtime-asserts -Rpass-missed -Rpass -save-optimization-record-path -save-optimization-record -sdk -static-executable -static-stdlib -suppress-warnings -swift-version -target-cpu -target-variant -target -use-ld -version -vfsoverlay -v -warn-implicit-overrides -warn-swift3-objc-inference-complete -warn-swift3-objc-inference-minimal -warnings-as-errors -working-directory -Xcc -Xlinker' 
     +_openstack:166> _cache_openstack_clnt_cmds[$service]='' 
     +_openstack:168> local cmd
     +_openstack:175> [[ -n '' ]]
     +_openstack:179> [[ -z '' && '' == -* ]]
     +_openstack:182> [[ -z '' ]]
     +_openstack:183> _values -w option
      +_values:3> local subopts opt usecc garbage
      +_values:5> subopts=( ) 
      +_values:6> zparseopts -D -a garbage 'C=usecc' 'O:=subopts' M: J: V: 1 2 n F: X:
      +_values:8> ((  0  ))
      +_values:10> compvalues -i -w option
_values:compvalues:10: not enough arguments
      +_values:156> curcontext=:complete:: 
      +_values:158> return 1
     +_openstack:192> return ret
   +_dispatch:64> [[ patterns = (all|*patterns*) ]]
   +_dispatch:64> return ret
 +_complete:142> _compskip='' 
 +_complete:144> return ret
+_main_complete:206> ((  _matcher_num++  ))
+_main_complete:189> _c_matcher=l:|=* r:|=*
+_main_complete:190> [[ 'l:|=* r:|=*' == +* ]]
+_main_complete:193> _matcher='l:|=* r:|=*' 
+_main_complete:196> _comp_mesg='' 
+_main_complete:197> [[ -n '' ]]
+_main_complete:202> _complete
 +_complete:7> local comp name oldcontext ret=1 service
 +_complete:8> typeset -T curcontext=:complete:: ccarray
 +_complete:10> oldcontext=:complete:: 
 +_complete:14> [[ -n '' ]]
 +_complete:96> comp=_first 
 +_complete:97> [[ -n _first ]]
 +_complete:98> service=-first- 
 +_complete:99> ccarray[3]=-first- 
 +_complete:100> eval _first
  +(eval):1> _first
 +_complete:100> ret=0 
 +_complete:101> [[ '' = all ]]
 +_complete:110> [[ -n '' ]]
 +_complete:114> ret=1 
 +_complete:115> [[ command = command ]]
 +_complete:116> curcontext=:complete:: 
 +_complete:117> _normal -s
  +_normal:3> local _comp_command1 _comp_command2 _comp_command skip
  +_normal:5> [[ -s = -s ]]
  +_normal:6> skip=( -s ) 
  +_normal:16> [[ -o BANG_HIST && '' = !*: || '' = "!*: ]]
  +_normal:29> [[ CURRENT -eq 1 ]]
  +_normal:38> _set_command
   +_set_command:6> local command
   +_set_command:8> command=swift 
   +_set_command:10> [[ -z swift ]]
   +_set_command:12> ((  0 + 0  ))
   +_set_command:15> [[ s = \= ]]
   +_set_command:19> [[ swift = ..#/* ]]
   +_set_command:23> [[ swift = */* ]]
   +_set_command:28> _comp_command1=swift 
   +_set_command:29> _comp_command2=/usr/bin/swift 
   +_set_command:30> _comp_command=swift 
  +_normal:40> _dispatch -s swift swift /usr/bin/swift -default-
   +_dispatch:3> local comp pat val name i ret=1 _compskip=''
   +_dispatch:4> local curcontext=:complete:: service str noskip
   +_dispatch:5> local -a match mbegin mend
   +_dispatch:9> [[ -s = -s ]]
   +_dispatch:10> noskip=yes 
   +_dispatch:11> shift
   +_dispatch:14> [[ -z yes ]]
   +_dispatch:16> curcontext=:complete:swift: 
   +_dispatch:18> shift
   +_dispatch:22> [[ '' != (all|*patterns*) ]]
   +_dispatch:24> str=swift
   +_dispatch:25> [[ -n swift ]]
   +_dispatch:26> service=swift 
   +_dispatch:24> str=/usr/bin/swift
   +_dispatch:25> [[ -n /usr/bin/swift ]]
   +_dispatch:26> service=/usr/bin/swift 
   +_dispatch:24> str=-default-
   +_dispatch:25> [[ -n -default- ]]
   +_dispatch:26> service=-default- 
   +_dispatch:45> ret=1 
   +_dispatch:46> str=swift
   +_dispatch:47> [[ -n swift ]]
   +_dispatch:51> str=swift 
   +_dispatch:52> name=swift 
   +_dispatch:53> comp=_openstack 
   +_dispatch:54> service=swift 
   +_dispatch:56> [[ -z _openstack ]]
   +_dispatch:56> break
   +_dispatch:61> [[ -n _openstack && swift != -default- ]]
   +_dispatch:62> _compskip=patterns 
   +_dispatch:63> eval _openstack
    +(eval):1> _openstack
     +_openstack:6> local curcontext=:complete:swift: state line expl ret=1
     +_openstack:8> local -a clnts_compl_new clnts_compl_old clnts_swift_like
     +_openstack:26> clnts_compl_new=( aodh barbican designate gnocchi openstack ) 
     +_openstack:27> clnts_compl_old=( ceilometer cinder cloudkitty glance heat ironic keystone magnum manila mistral monasca murano neutron nova sahara senlin trove ) 
     +_openstack:28> clnts_swift_like=( swift ) 
     +_openstack:32> ((  ! 1  ))
     +_openstack:41> local -a conn_opts
     +_openstack:42> local opt arg word
     +_openstack:44> [[ swift == openstack ]]
     +_openstack:59> [[ -n '' ]]
     +_openstack:124> [[ -n '' ]]
     +_openstack:161> [[ -n swift ]]
     +_openstack:162> [[ -z '' ]]
     +_openstack:164> _cache_openstack_clnt_outputs[$service]=     +_openstack:164> swift --help
     +_openstack:164> _cache_openstack_clnt_outputs[$service]=$'OVERVIEW: Swift compiler\n\nUSAGE: swift [options] <inputs>\n\nOPTIONS:\n  -assert-config <value>  Specify the assert_configuration replacement. Possible values are Debug, Release, Unchecked, DisableReplacement.\n  -continue-building-after-errors\n                          Continue building, even after errors are encountered\n  -debug-info-format=<value>\n                          Specify the debug info format type to either \'dwarf\' or \'codeview\'\n  -debug-info-store-invocation\n                          Emit the compiler invocation in the debug info.\n  -debug-prefix-map <value>\n                          Remap source paths in debug info\n  -D <value>              Marks a conditional compilation flag as true\n  -enforce-exclusivity=<enforcement>\n                          Enforce law of exclusivity\n  -framework <value>      Specifies a framework which should be linked against\n  -Fsystem <value>        Add directory to system framework search path\n  -F <value>              Add directory to framework search path\n  -gdwarf-types           Emit full DWARF type info.\n  -gline-tables-only      Emit minimal debug info for backtraces only\n  -gnone                  Don\'t emit debug info\n  -g                      Emit debug info. This is the preferred setting for debugging with LLDB.\n  -help                   Display available options\n  -index-store-path <path>\n                          Store indexing data to <path>\n  -I <value>              Add directory to the import search path\n  -j <n>                  Number of commands to execute in parallel\n  -L <value>              Add directory to library link search path\n  -l<value>               Specifies a library which should be linked against\n  -module-cache-path <value>\n                          Specifies the Clang module cache path\n  -module-link-name <value>\n                          Library to link against when using this module\n  -module-name <value>    Name of the module to build\n  -nostdimport            Don\'t search the standard library import path for modules\n  -num-threads <n>        Enable multi-threading and specify number of threads\n  -Onone                  Compile without any optimization\n  -Osize                  Compile with optimizations and target small code size\n  -Ounchecked             Compile with optimizations and remove runtime safety checks\n  -O                      Compile with optimizations\n  -remove-runtime-asserts Remove runtime safety checks.\n  -Rpass-missed=<value>   Report missed transformations by optimization passes whose name matches the given POSIX regular expression\n  -Rpass=<value>          Report performed transformations by optimization passes whose name matches the given POSIX regular expression\n  -save-optimization-record-path <value>\n                          Specify the file name of any generated YAML optimization record\n  -save-optimization-record\n                          Generate a YAML optimization record file\n  -sdk <sdk>              Compile against <sdk>\n  -static-executable      Statically link the executable\n  -static-stdlib          Statically link the Swift standard library\n  -suppress-warnings      Suppress all warnings\n  -swift-version <vers>   Interpret input according to a specific Swift language version number\n  -target-cpu <value>     Generate code for a particular CPU variant\n  -target-variant <value> Generate code that may run on a particular variant of the  deployment target\n  -target <value>         Generate code for the given target\n  -use-ld=<value>         Specifies the linker to be used\n  -version                Print version information and exit\n  -vfsoverlay <value>     Add directory to VFS overlay file\n  -v                      Show commands to run and use verbose output\n  -warn-implicit-overrides\n                          Warn about implicit overrides of protocol members\n  -warn-swift3-objc-inference-complete\n                          Warn about deprecated @objc inference in Swift 3 for every declaration that will no longer be inferred as @objc in Swift 4\n  -warn-swift3-objc-inference-minimal\n                          Warn about deprecated @objc inference in Swift 3 based on direct uses of the Objective-C entrypoint\n  -warnings-as-errors     Treat warnings as errors\n  -working-directory <path>\n                          Resolve file paths relative to the specified directory\n  -Xcc <arg>              Pass <arg> to the C/C++/Objective-C compiler\n  -Xlinker <value>        Specifies an option which should be passed to the linker' 
     +_openstack:165> _cache_openstack_clnt_opts[$service]='-assert-config -continue-building-after-errors -debug-info-format -debug-info-store-invocation -debug-prefix-map -D -enforce-exclusivity -framework -Fsystem -F -gdwarf-types -gline-tables-only -gnone -g -help -index-store-path -I -j -L -l<value> -module-cache-path -module-link-name -module-name -nostdimport -num-threads -Onone -Osize -Ounchecked -O -remove-runtime-asserts -Rpass-missed -Rpass -save-optimization-record-path -save-optimization-record -sdk -static-executable -static-stdlib -suppress-warnings -swift-version -target-cpu -target-variant -target -use-ld -version -vfsoverlay -v -warn-implicit-overrides -warn-swift3-objc-inference-complete -warn-swift3-objc-inference-minimal -warnings-as-errors -working-directory -Xcc -Xlinker' 
     +_openstack:166> _cache_openstack_clnt_cmds[$service]='' 
     +_openstack:168> local cmd
     +_openstack:175> [[ -n '' ]]
     +_openstack:179> [[ -z '' && '' == -* ]]
     +_openstack:182> [[ -z '' ]]
     +_openstack:183> _values -w option
      +_values:3> local subopts opt usecc garbage
      +_values:5> subopts=( ) 
      +_values:6> zparseopts -D -a garbage 'C=usecc' 'O:=subopts' M: J: V: 1 2 n F: X:
      +_values:8> ((  0  ))
      +_values:10> compvalues -i -w option
_values:compvalues:10: not enough arguments
      +_values:156> curcontext=:complete:: 
      +_values:158> return 1
     +_openstack:192> return ret
   +_dispatch:64> [[ patterns = (all|*patterns*) ]]
   +_dispatch:64> return ret
 +_complete:142> _compskip='' 
 +_complete:144> return ret
+_main_complete:206> ((  _matcher_num++  ))
+_main_complete:208> [[ -n '' ]]
+_main_complete:210> ((  _completer_num++  ))
+_main_complete:166> tmp=_ignored
+_main_complete:168> [[ -n '' ]]
+_main_complete:170> [[ _ignored = *:-* ]]
+_main_complete:173> [[ _ignored = *:* ]]
+_main_complete:177> _completer=ignored 
+_main_complete:180> curcontext=:ignored:: 
+_main_complete:181> zstyle -t :completion::ignored::: show-completer
+_main_complete:184> zstyle -a :completion::ignored::: matcher-list _matchers
+_main_complete:187> _matcher_num=1 
+_main_complete:188> _matcher='' 
+_main_complete:189> _c_matcher=m:{a-zA-Z}={A-Za-z}
+_main_complete:190> [[ 'm:{a-zA-Z}={A-Za-z}' == +* ]]
+_main_complete:193> _matcher='m:{a-zA-Z}={A-Za-z}' 
+_main_complete:196> _comp_mesg='' 
+_main_complete:197> [[ -n '' ]]
+_main_complete:202> _ignored
 +_ignored:5> [[ _matcher_num -gt 1 || 0 -eq 0 ]]
 +_ignored:5> return 1
+_main_complete:206> ((  _matcher_num++  ))
+_main_complete:189> _c_matcher=r:|=*
+_main_complete:190> [[ 'r:|=*' == +* ]]
+_main_complete:193> _matcher='r:|=*' 
+_main_complete:196> _comp_mesg='' 
+_main_complete:197> [[ -n '' ]]
+_main_complete:202> _ignored
 +_ignored:5> [[ _matcher_num -gt 1 ]]
 +_ignored:5> return 1
+_main_complete:206> ((  _matcher_num++  ))
+_main_complete:189> _c_matcher=l:|=* r:|=*
+_main_complete:190> [[ 'l:|=* r:|=*' == +* ]]
+_main_complete:193> _matcher='l:|=* r:|=*' 
+_main_complete:196> _comp_mesg='' 
+_main_complete:197> [[ -n '' ]]
+_main_complete:202> _ignored
 +_ignored:5> [[ _matcher_num -gt 1 ]]
 +_ignored:5> return 1
+_main_complete:206> ((  _matcher_num++  ))
+_main_complete:208> [[ -n '' ]]
+_main_complete:210> ((  _completer_num++  ))
+_main_complete:213> curcontext=::: 
+_main_complete:214> [[ '' = keep ]]
+_main_complete:220> nm=0 
+_main_complete:223> [[ '' = keep || nm -gt 1 ]]
+_main_complete:338> [[ nm -lt 1 && -n '' ]]
+_main_complete:341> [[ nm -eq 0 && -z '' && 0 -ne 0 ]]
+_main_complete:361> [[ -n '' ]]
+_main_complete:368> [[ '' = always || '' = ?* ]]
+_main_complete:374> [[ '' = keep ]]
+_main_complete:380> ((  1  ))
+_main_complete:381> ZLS_COLORS='' 
+_main_complete:389> funcs=( ) 
+_main_complete:390> comppostfuncs=( ) 
+_main_complete:395> _lastcomp=( list_lines 0 all_quotes '\' nmatches 0 restore auto context command vared '' unambiguous '' list_max 100 unambiguous_cursor 1 list ambiguous insert_positions '' unambiguous_positions '' exact '' to_end match last_prompt yes pattern_insert menu ignored 0 insert automenu-unambiguous ) 
+_main_complete:396> _lastcomp[nmatches]=0 
+_main_complete:397> _lastcomp[completer]=ignored 
+_main_complete:398> _lastcomp[prefix]='' 
+_main_complete:399> _lastcomp[suffix]='' 
+_main_complete:400> _lastcomp[iprefix]='' 
+_main_complete:401> _lastcomp[isuffix]='' 
+_main_complete:402> _lastcomp[qiprefix]='' 
+_main_complete:403> _lastcomp[qisuffix]='' 
+_main_complete:404> _lastcomp[tags]='' 
+_main_complete:406> return ret
+_complete_debug:22> integer ret=1
+_complete_debug:23> unsetopt xtrace
</pre>
</details>

**Comment by skagedal** [comment]
I managed to solve the problem by updating `zsh`. So instead of using the system-bundled `zsh` (which I would in some ways prefer, since it feels safer and simpler) I now installed it with Homebrew:

`brew install zsh`

I then set up Terminal to use `/usr/local/bin/zsh` as its startup shell. An alternative is to add this line to `/etc/shells` and then use `chsh -s /usr/local/bin/zsh`, but this felt better at the moment. 

I also added `swiftpm` to my plugins in `.zshrc` and now everything is great.
