### ISSUE TITLE
Z Plugin: mv: rename /Users/mhluska/.z.12601 to /Users/mhluska/.z: No such file or directory

### ISSUE THREAD

**Issue by mhluska** [robbyrussell/oh-my-zsh#7094]
When I install the Z plugin through oh-my-zsh using `plugins=(z)`, in `.zshrc` I sometimes see this error:

```
mv: rename /Users/mhluska/.z.12601 to /Users/mhluska/.z: No such file or directory
```

It mainly happens when I hold down the enter key for a while in the terminal. This doesn't happen when I install the plugin the conventional way using `brew install z`.

**Comment by hardianlawi** [comment]
This also happens to me sometimes when I move to my `Downloads` directory.

**Comment by mcornella** [comment]
Can you post the output of `ls -l ~/.z{,.*}(N)`?

**Comment by mcornella** [comment]
Nevermind, by what you said 

> It mainly happens when I hold down the enter key for a while in the terminal.

It looks like this is a race condition, where multiple runs of the _z command will use the same tempfile and one of those executions will clobber or delete another one's tempfile. This is due to the fact that the _z utility function is run asynchronously:
```
_z_precmd() {
	(_z --add "${PWD:a}" &)
}
```

and it happens despite the use of `$RANDOM` to generate pseudo-unique names for the tempfile. The ultimate culprit is that the function is run inside a subshell, of which the [zsh documentation](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-RANDOM) says the following:

> The values of RANDOM form an intentionally-repeatable pseudo-random sequence; **subshells that reference RANDOM will result in identical pseudo-random values** _unless the value of RANDOM is referenced or seeded in the parent shell in between subshell invocations_.

meaning, if we reference `$RANDOM` inside a subshell like `_z` does, multiple executions will get the same `$RANDOM` value, using the same filename and thus stepping on each other's toes.

A possible fix to that is referencing `$RANDOM` in the parent shell after each subshell, as the documentation says, like so:
```
_z_precmd() {
	(_z --add "${PWD:a}" &)
	: $RANDOM
}
```

As you already hinted at, a way to reproduce this is holding down the enter key. It has to be in a directory different from `$HOME` though. This happens because the function is called before each printing of the prompt, meaning that another fix to this problem would be to [use the chpwd hook](https://github.com/rupa/z/issues/210) instead of the precmd hook.

For now, you can add to your zshrc file the following
```
_z_precmd() {
	(_z --add "${PWD:a}" &)
	: $RANDOM
}
```

while waiting for an upstream fix.

**Comment by mcornella** [comment]
Waiting on https://github.com/rupa/z/pull/247 to be merged.

**Comment by mcornella** [comment]
The fix was merged in OMZ some time ago.

**Comment by djvs** [comment]
Still dealing with this bug years later.  Oh-my-zsh on git master, a7f5170d68c0b75a9864763a90ac11e51ec67c81

**Comment by mcornella** [comment]
Please run `typeset -f -t _z_precmd` and post the output when this error appears. You can also use `script` to log the command line to reference it later and be able to more easily search for the error message.

**Comment by mrdima** [comment]
With the current Oh-my-zsh still occuring for me as well. I do have the output of typeset -f -t _z_precmd but prefer not to post all of the 500+ lines of content, would be happy to email it or so.

**Comment by mcornella** [comment]
You can email it to me, my email address is in [my profile](https://github.com/mcornella).

**Comment by dimitriars** [comment]
emailed, please note that I entered typeset -f -t _z_precmd after the error message occurred, not before, hope that's ok

**Comment by mcornella** [comment]
It's weird to me that you get the same tempfile in both `_z_precmd` invocations:
```
~/github  cd mv: cannot stat '/home/user/.z.13775': No such file or directory
 
~/github  typeset -f -t _z_precmd
+_z_precmd:1> _z --add /home/user/github                                                                                                                                                
+_z:2> local datafile=/home/user/.z
+_z:5> [ -h /home/user/.z ']'
+_z:8> [ -z '' -a -f /home/user/.z -a '!' -O /home/user/.z ']'
+_z:20> [ --add '=' --add ']'
+_z:21> shift
+_z:24> [ /home/user/github '=' /home/user ']'
+_z:27> local exclude
+_z:28> exclude=
+_z:29> case /home/user/github (\*)
+_z:33> local tempfile=/home/user/.z.13775
```

This means that `$RANDOM`, used to generate the unique tempfile name, is not getting refreshed. Are you sure you're on a recent OMZ version? What's the output of `which _z_precmd`?

**Comment by dimitriars** [comment]
Yes, my o zsh prompt me to update regularly, I think it was this or last week that I updated again, I normally always do this directly. I'm running on Ubuntu 20.10, but it was the same on older versions.
Also, I haven't really tried to replicate it with 1 terminal...I do use terminator with multiple zsh shells (which load my o zsh from the .zshrc file)...they shouldn't interfere right?

which _z_precmd
_z_precmd () {
	(
		_z --add "${PWD:A}" &
	)
}

**Comment by mcornella** [comment]
This shows that you don't get the OMZ change, which would have [a `: $RANDOM` line after the subshell](https://github.com/ohmyzsh/ohmyzsh/blob/fae34b383d6432f7118c2ad082224f6d27d51221/plugins/z/z.sh#L234).

Run this `whence -v _z_precmd` to know which file you're getting the function from. Also make sure that you're on the latest OMZ commit (at the time of writing this, fae34b383d6432f7118c2ad082224f6d27d51221) by going into the `$ZSH` folder and running `git show`.

**Comment by dimitriars** [comment]
It was pretty new (commit from January 10), but I think I found the issue. I included in my .zshrc file a file .zsh/z.sh and that was old. The z plugin wasn't enabled in the plugins variable, only git ... so I guess that's why it was never updated. Removed the .zsh directory, removed the inclusion it from my .zshrc and added it to plugins ... Don't know why the z.sh was included manually ... did that somewhere in 2019 ...
Don't know if this also the issue for @djvs 
Thanks for the help!
